title: Blog de Hacking
author: K0Hack
email: 
description: > # this means to ignore newlines until "show_exerpts:"
  Blog Personal de K0Hack sobre Conceptos
  Hacking Etico // HTB // TryHackMe // Resumenes de Hacking
  // Herramientas para distintas tareas.
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 4
paginate_path: "/blog/page:num"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
      url: https://Ki-pro.github.io
      icon: github-square
      color: red

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-theme-cayman

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain
